services:
  client:
    build: ./client
    ports:
      - "5173:5173"  #Dev port # 4173 preview port, not dev
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/booksDB
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: